# -*- coding: utf-8 -*-
"""iceCream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRVWzFBSBPx6NDlZyZSorZkKDmuVI9A3
"""

import pandas as pd

IceCream = pd.read_csv('https://github.com/ardbramantyo/Ice-Cream-Revenue-Prediction/raw/main/Dataset/IceCreamData.csv')

IceCream.head()

IceCream.tail()

IceCream.describe()

IceCream.info()

IceCream.columns

y =IceCream['Revenue']

x = IceCream[['Temperature']]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

x_train.shape

from sklearn.linear_model import LinearRegression

regressor = LinearRegression(fit_intercept = True)

regressor.fit(x_train,y_train)

print('Linear Model Coefficient (m): ', regressor.coef_)
print('Linear Model Coefficient (b): ', regressor.intercept_)

y_predict = regressor.predict( x_test)
y_predict

y_test





